spring:
  application:
    name: springsecurityexample
#  InMemoryUserDetailsManager 등 UserDetailsManager 빈을 구성하면 yml 파일에 설정한 정보로는 인증 불가능
#  security:
#    user: # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.security
#      name: admin
#      password: admin
