spring:
  application:
    name: springsecurityexample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurityexample
    username: springsecurity
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
#  InMemoryUserDetailsManager 등 UserDetailsManager 빈을 구성하면 yml 파일에 설정한 정보로는 인증 불가능
#  security:
#    user: # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.security
#      name: admin
#      password: admin

#logging:
#  level:
#    org.springframework.security.web.FilterChainProxy: "debug" # FilterChainProxy 로그 레벨 설정
    # 추가로 FilterChainProxy의 내부 클래스 VirtualFilterChain의 doFilter()에 중단점 설정하고 확인 진행
